# This file is used to build the firmware for the Nice! Nano v2 with Cygnus shields.
---
include:
  - board: "nice_nano_v2"
    shield: "cygnus_left"
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: "zmk-usb-logging"
  - board: "nice_nano_v2"
    shield: "cygnus_right"
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: "zmk-usb-logging"
