# This file is used to build the firmware for the Nice! Nano v2.
---
include:
  # Cygnus
  - board: "nice_nano//zmk"
    shield: "cygnus_left"
    artifact-name: "cygnus_left"
    snippet: studio-rpc-usb-uart
  - board: "nice_nano//zmk"
    shield: "cygnus_right"
    artifact-name: "cygnus_right"
    snippet: studio-rpc-usb-uart
  # Oulico Skeletyl
  - board: "nice_nano//zmk"
    shield: "skeletyl_left"
    artifact-name: "skeletyl_left"
    snippet: studio-rpc-usb-uart
  - board: "nice_nano//zmk"
    shield: "skeletyl_right"
    artifact-name: "skeletyl_right"
    snippet: studio-rpc-usb-uart
  # Settings reset (flash wipe utility)
  - board: "nice_nano//zmk"
    shield: "settings_reset"
    artifact-name: "settings_reset"
