# This file is used to build the firmware for the Nice! Nano v2 with Cygnus shields.
---
include:
  - board: nice_nano_v2
    shield: cygnus_left
  - board: nice_nano_v2
    shield: cygnus_right
  - board: nice_nano_v2
    shield: settings_reset
