# Central (left) specific settings
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

# Peripheral battery level proxy (central이 peripheral 배터리를 가져와서 BLE로 노출)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
